spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mpro?serverTimezone=UTC&characterEncoding=UTF-8
    username: mpro
    password: mpro1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  application:
    name: m-user


token:
  expired:
    base: 86400000
    refresh: 87000000

service:
  auth:
    url: http://localhost:8081/

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8080